#!/bin/bash -x

if [[ ${DOCKER_TAG} == latest ]]; then
    EVERSION=27.2
    ORG_RELEASE=9.4.4
else
    EVERSION=${DOCKER_TAG%-*}
    ORG_RELEASE=${DOCKER_TAG#*-}
fi

docker build --build-arg EVERSION=${EVERSION} --build-arg ORG_RELEASE=${ORG_RELEASE} -f Dockerfile -t $IMAGE_NAME .
